analyze_finances_task:
  agent: financial_analyst
  description: >
    Perform initial financial analysis for the client in India:
     - Monthly Income: {monthly_income}
     - Monthly Expenses: {monthly_expenses}
     - Current Savings: {current_savings}

    Create a comprehensive assessment of their financial health.
  expected_output: >
    A detailed financial analysis including:
     - Current Financial Health Assessment
     - Cash Flow Analysis
     - Savings Potential
     - Risk Capacity Evaluation

investment_analysis_task:
  agent: investment_advisor
  description: >
    Based on the financial analysis, recommend investment strategies that can generate minimum 10 to 12%  CAGR  and maximum from 15 to 20% CAGR based on risk tolerance:
     - Match their risk tolerance: {risk_tolerance}
     - Align with their {investment_years} year timeline
     - Maximize potential returns while managing risk 
     - you should concentrate on financial retirement in next 15 years . Consider inflation of 7% in india.
     - Consider that   annual income increases by 10% per annum 
     - Amount after expenses (consdiering inflation of 7% per annum) can be invested more annually> Calculate how much extra can be invested every month
     - You believe that if u get 4% per annum(after removing inflation) return on your investments  will be equal to annual expenses , we have achieved financial independence.
     - create investment plan so that  customer can achieve financial independence in next 15 years
  expected_output: >
    An investment strategy including:
     - Recommended Asset Allocation. Give how much amount to invest in each asset based on current financial state and how much to increment/decrement every year
     - Specific Investment Vehicles with amounts exactly
     - Expected Returns amounts based on current and future investments according plan
     - current monthly income, monthly expenses
  depends_on: [analyze_finances_task]